package main

import (
	"flag"
	"fmt"
	"html/template"
	"math/rand"
	"os"
	"strings"
)

type PlayerName struct {
	User    string
	English string
	Dwarf   string
}

type Player struct {
	Name         PlayerName
	Profession   string
	Burrow       string
	Scum         bool
	RoleName     string
	RoleWiki     string
	RoleFlavor   string
	WinCondition string
}

var tmpl = template.Must(template.New("").Funcs(template.FuncMap{
	"ShufflePlayers": func() []Player { panic("unreachable") },
	"fields":         strings.Fields,
	"lower":          strings.ToLower,
}).Parse(`This post is generated by dwarf-mafia for the benefit of Club Ded. Do not share the contents of this post outside of Club Ded.

# Role summary

{{range .Players -}}
{{if not .Scum -}}
- {{.Name.User}}, {{.RoleWiki}}
{{end -}}
{{end -}}
{{range .Players -}}
{{if .Scum -}}
- {{.Name.User}}, {{.RoleWiki}}
{{end -}}
{{end}}
# Burrow summary
{{range $b := .Burrows}}
## {{$b}}

{{range $.Players -}}
{{if eq $b .Burrow -}}
- {{if .Scum}}*{{end}}{{.Name.User}}, <abbr title="{{.Name.English}}">{{.Name.Dwarf}}</abbr>, {{.Profession}}{{if .Scum}}*{{end}}
{{end -}}
{{end -}}
{{end}}
# Welcome private messages

{{range .Players -}}
## {{.Name.User}}

{{block "welcome" . -}}
Hello, **<abbr title="{{.Name.English}}">{{.Name.Dwarf}}</abbr>**! You are a <a href="http://dwarffortresswiki.org/DF2014:{{.Profession}}">{{.Profession}}</a> who works and sleeps in the **{{.Burrow}} <a href="http://wiki.mafiascum.net/index.php?title=Neighbor">burrow</a>**.

You are **<a href="http://wiki.mafiascum.net/index.php?title={{.RoleWiki}}">{{.RoleName}}</a>**. {{.RoleFlavor}} You win if **{{.WinCondition}}**.

{{end -}}
{{end -}}

# Opening posts

## Main Thread

Welcome to the sixth installment of WTDWTF Mafia: Dwarf Fortress Mafia!

The game's threads are all in [this category](https://what.thedailywtf.com/category/31/current-game) or one of its subcategories.

I'm your GM, @{{.Moderator}}, and I have absolutely no idea what I'm doing.

### The rules

1. If by some miracle you're able to post in this thread and you aren't a living player, do **not** post and report the situation to me. If you want to comment on the ongoing game or berate a player for being an idiot, PM me to apply to the official peanut gallery.
2. Important: **do not report posts in any faction/private thread**. There are moderators playing, and reporting a post makes it visible to them regardless of permissions. Summon one of the site administrators instead.
3. When in doubt, ask questions via PM. I may or may not answer depending on the nature of the question, but you can be sure all communication via chat will be kept private.
4. Each player should have obtained a role card via PM. The role card contains:
  - Your flavor role, or "profession". This information has no gameplay value, and you can share it freely for roleplay purposes.
  - Your dwarf name. This is used for roleplay purposes, and just so you don't have to remember them, I've made @-mentions and post author names in this thread automatically expand to contain their roleplaying name.
  - Your neighborhood, or [burrow](http://dwarffortresswiki.org/index.php/DF2014:Burrow). You may chat freely in your burrow.
  - One or more of your in-game roles. **The roles have flavor names** for roleplay purposes, but each player should have a link to the MafiaScum wiki explaining what hides under the flavor.
5. You are **not allowed to quote your Role PM directly**, or any other private communication with me for that matter. You can paraphrase it, you can make things up about your role, you can invent a role, but you can't post a quote from your role card.
  - Flavor such as your dwarf name and profession are excluded from this rule.
6. You're **heavily encouraged to save your Role PM** outside of the chat. NodeBB's private messaging system only displays the most recent 50 messages, and you definitely don't want to lose that post.
7. This is a **semi-open setup game**. The entire setup was generated with [dwarf-mafia](https://github.com/BenLubar/dwarf-mafia), but the seed is random. I will not answer questions about the presence of specific roles in this setup, but you can check the list of possibilities in the source code.
  - Of note is that we are playing with a subset of MafiaScum's "Normal" ruleset. There are no Jesters in this game. That player who's being an idiot is, in fact, an idiot.
8. This is a **non-bastard game**. A full role PM will be revealed upon death unless otherwise specified, and the GM will not lie to you, deceive you, give you up, let you down, run around, and desert you.
9. This is a **flavor game**. There's no guarantee that commonly-known Mafia terminology will be used.
10. You can quit the game at any time, either by PM or by public announcement. Abuse of this mechanism to gain advantage will have severe consequences that will never be the same.
11. **Do not edit, boomark, or like posts**. You shouldn't be able to, but if you manage to find a clever way to do it anyway, Club Ded will not be amused.
12. **Do not contact other players or Club Ded members to discuss the game** outside of threads marked for this purpose, and do not discuss the game anywhere but in those threads. Armok is watching.
13. Do not encrypt, obfuscate or alter your posts, post in lojban, or use content which can be altered (outside-hosted images, iframely, etc.). Report all posts which infringe this rule via a PM to me.
14. <big><big>**The night phase is instantaneous**. Night actions are submitted via PM (or in your faction's thread if you're in a faction with a night action). The last action to be submitted during a day takes place the moment that day ends. The day ends when a majority of living dwarves vote to lynch a player or 1 week of real time has passed.</big></big>
15. **You have to post in the main thread once every 24 hours**. Note that this is Earth hours, not the hours that take half a second in normal Dwarf Fortress.

**To vote**, use the following commands:

@ben_lubot vote @player
@ben_lubot no-lynch
@ben_lubot unvote


**The game will begin shortly.** You'll know when that happens because I'll post the intro text, obviously. Feel free to comment on the rules if anything's unclear before that.

Each player will receive their Role PM shortly.

### List of living players:

{{range .Players -}}
- @{{.Name.User}}
{{end}}

## Start of day 1

### Mafia VI - Dwarf Fortress Mafia

{{with $d := ShufflePlayers -}}
*"It was inevitable."*

@{{(index $d 0).Name.User}} is overcome by grief. @{{$.Moderator}}, the mayor of Ganfamthut is dead. Killed in his sleep and drained of blood. There is a vampire lurking somewhere in the fortress. Maybe even more than one! @{{(index $d 0).Name.User}} screams for help. @{{(index $d 1).Name.User}} and @{{(index $d 2).Name.User}} are nearby and arrive first.

*"It was inevitable." "It was inevitable."*

The three of them haul @{{$.Moderator}}'s corpse to the cemetary. Ornate slabs describe the many soldiers that died in sieges and megabeast attacks. There are even finely decorated coffins for dogs and cats that died of old age. And some smaller coffins for babies that were burnt alive by dragons. But the only unused coffin is completely undecorated. @{{(index $d 1).Name.User}} sighs. This will have to do.

**@{{$.Moderator}} was found dead on Day 1!**

> Hello, **<abbr title="Oar Armorexit">Mebzuth Tosidonrel</abbr>**! You are an <a href="http://dwarffortresswiki.org/DF2014:administrator">administrator</a> who works and sleeps in the **mayoral office**.
>
> You are **<a href="http://dwarffortresswiki.org/index.php/Mayor">mayor</a> who had an <a href="http://dwarffortresswiki.org/index.php/Unfortunate_accident">unfortunate accident</a>**. You cannot win. ***Losing is fun.***

Back in the mayor's office, everyone searches for clues. @{{(index $d 3).Name.User}} finds a book wedged between the bed and a wall.

*"Could It Be Cats? A 113-page autobiography by @{{$.Moderator}}"*

@{{(index $d 4).Name.User}} is impatient. "What are you waiting for? Read it!"

> ### Could It Be Cats?
>
> In 2016, I died.
>
> *The remaining 112 pages are blank.*

@{{(index $d 5).Name.User}} chimes in. "Well, he was a good mayor, but that's some terrible writing."

"Maybe he died while he was trying to write it," offers @{{(index $d 6).Name.User}}.

@{{(index $d 2).Name.User}} turns to the group. "Killed by a vampire. He was pale as bone and had bite marks on his neck. This isn't a normal murder. The killer is somewhere in this room."

A silence covers the room like a blanket. There will be many more deaths before this is over.

**It is now Day 1! You have 7 days to find the killer before they strike again!**
{{end}}

## Burrows

{{range $b := .Burrows -}}
### {{.}}

This is the **{{.}}** burrow. You may discuss anything game related in this channel at any time, but beware that there might be vampires among your ranks. A list of dwarves assigned to this burrow follows:

{{range $.Players -}}
{{if eq $b .Burrow -}}
- @{{.Name.User}}, {{.Profession}}
{{end -}}
{{end}}
{{end -}}

# <del>CSS</del><ins>LESS</ins>

` + "```" + `
[data-tid="???"] {
	&>[data-username="{{.Moderator}}"] { background-color: rgba(255,255,0,0.25); }
	a[itemprop="author"][data-username="{{.Moderator}}"] { &:before { content: 'Mebzuth “@'; } &:after { content: '” Tosidonrel'; } }
	a.plugin-mentions-a[href="https://what.thedailywtf.com/user/{{lower .Moderator}}"] { &:before { content: 'Mebzuth “'; } &:after { content: '” Tosidonrel'; } }
{{- range .Players}}
	a[itemprop="author"][data-username="{{.Name.User}}"] { &:before { content: '{{index (fields .Name.Dwarf) 0}} “@'; } &:after { content: '” {{index (fields .Name.Dwarf) 1}}'; } }
	a.plugin-mentions-a[href="https://what.thedailywtf.com/user/{{lower .Name.User}}"] { &:before { content: '{{index (fields .Name.Dwarf) 0}} “'; } &:after { content: '” {{index (fields .Name.Dwarf) 1}}'; } }
{{- end}}
}
` + "```" + `

`))

func main() {
	seed := flag.Int64("seed", 0, "seed for randomness")
	moderator := flag.String("gm", "ben_lubar", "game moderator")

	flag.Parse()

	if flag.NArg() == 0 {
		fmt.Fprintln(os.Stderr, "need 1 or more username on the command line")
		os.Exit(1)
	}

	// http://dwarffortresswiki.org/index.php/DF2014:Unit_type_token, but
	// without any of the meta-professions or the useless professions.
	professions := []string{"miner", "carpenter", "bowyer", "woodcutter", "engraver", "mason", "animal trainer", "hunter", "trapper", "furnace operator", "weaponsmith", "armorer", "blacksmith", "metalcrafter", "gem cutter", "gem setter", "woodcrafter", "stonecrafter", "leatherworker", "bone carver", "weaver", "clothier", "glassmaker", "potter", "glazer", "wax worker", "strand extractor", "fisherdwarf", "fish cleaner", "cheese maker", "milker", "cook", "thresher", "miller", "butcher", "tanner", "dyer", "planter", "herbalist", "brewer", "soap maker", "potash maker", "lye maker", "wood burner", "shearer", "spinner", "beekeeper", "mechanic", "siege engineer", "siege operator", "pump operator", "clerk", "trader", "architect", "diagnostician", "bone doctor", "suturer", "surgeon", "peasant", "gelder", "bard", "dancer", "sage", "philosopher", "mathematician", "historian", "astronomer", "naturalist", "chemist", "geographer", "scribe", "papermaker", "bookbinder", "tavern keeper"}
	burrows := []string{"crimson", "scarlet", "maroon"}

	r := rand.New(rand.NewSource(*seed))

	var players []Player

	for _, username := range flag.Args() {
		english, dwarf := GenerateName(r)
		profession := professions[r.Intn(len(professions))]
		players = append(players, Player{
			Name: PlayerName{
				User:    username,
				English: english,
				Dwarf:   dwarf,
			},
			Profession:   profession,
			RoleName:     "an average citizen",
			RoleWiki:     "Townie",
			RoleFlavor:   "",
			WinCondition: "all the vampires have been eliminated or nothing can prevent this from occurring",
		})
	}

	burrowers := r.Perm(flag.NArg())
	burrowShuffle := r.Perm(len(burrows))
	for i, j := range burrowers {
		players[j].Burrow = burrows[burrowShuffle[i%len(burrows)]]
	}

	const goonFlavor = "Each night you may choose one citizen to feed on. Only one vampire feeds per night to avoid suspicion."

	// From http://wiki.mafiascum.net/index.php?title=Normal_Game&oldid=119436#Roles
	type Role struct{ Name, Wiki, Flavor string }

	rolesTown := []Role{
		{
			Name:   "a night watchdwarf",
			Wiki:   "Bodyguard",
			Flavor: "Each night, you may select one dwarf to protect. If they are in danger, you will give your life to protect theirs.",
		},
		{
			Name:   "a coward",
			Wiki:   "Commuter",
			Flavor: "Each night, you may choose to sleep in your hiding place far from the fortress. This makes you immune to all night actions. You may only use this ability up to three times in the course of the game.",
		},
		{
			Name:   "an amateur detective",
			Wiki:   "Sane_Cop",
			Flavor: "Each night, you may select one dwarf to investigate. If successful, you will determine whether they are a vampire.",
		},
		{
			Name:   "a doctor",
			Wiki:   "Doctor",
			Flavor: "Each night, you may select one dwarf to protect. Your target will be protected from one night kill attempt. You will not be told if your protection was successful.",
		},
		{
			Name:   "a follower",
			Wiki:   "Follower",
			Flavor: "Each night, you may select one dwarf to watch. If they perform an action during that night, you will know what the action was, but not who they targeted.",
		},
		// Note: skipped Gunsmith because Dwarf Fortress doesn't have
		// guns and it would just make things confusing
		{
			Name:   "a dabbler in many trades",
			Wiki:   "Jack_of_All_Trades",
			Flavor: "Each night, you may select one dwarf to investigate, protect, kill, or distract. Investigating a dwarf tells you that dwarf's role, protecting a dwarf blocks one night kill attempt on them, killing a dwarf is murder, and distracting a dwarf prevents their night action. Each of these abilities may only be used once during the game.",
		},
		{
			Name:   "the sheriff",
			Wiki:   "Jailkeeper",
			Flavor: "Each night, you may lock one dwarf in a cage. This prevents them from acting but also prevents them from being killed. You may not lock yourself in a cage.",
		},
		{
			Name:   "a door enthusiast",
			Wiki:   "Motion_Detector",
			Flavor: "Each night, you may select one dwarf to watch. You will know if someone entered or left their bedroom after they were asleep, but not who or for what reason.",
		},
		// Note: skipped Neapolitan as we have a lot of power roles.
		// Note: skipped Neighbor and Neighborizer as the setup already
		// includes neighborhoods for all players.
		{
			Name:   "a drunk",
			Wiki:   "Roleblocker",
			Flavor: "Each night, you may select one dwarf to distract. A distracted dwarf will forget to perform an action at night.",
		},
		{
			Name:   "a detective",
			Wiki:   "Rolecop",
			Flavor: "Each night, you may select one dwarf to investigate. If successful, you will determine their role.",
		},
		{
			Name:   "terribly flatulent",
			Wiki:   "Rolestopper",
			Flavor: "Each night, you may select one dwarf to visit. Your farts smell so terrible that nobody will come near them.",
		},
		{
			Name:   "a stalker",
			Wiki:   "Tracker",
			Flavor: "Each night, you may select one dwarf to follow. If successful, you will know who they visited during the night, but not what they did during the visit.",
		},
		{
			Name:   "a graverobber",
			Wiki:   "Universal_Backup",
			Flavor: "You will inherit the special ability of the first dwarf to die with one.",
		},
		// Note: skipped Vanilla Cop
		{
			Name:   "a voyeur",
			Wiki:   "Voyeur",
			Flavor: "Each night, you may select one dwarf to watch. If they are targeted by an action during that night, you will know what the action was, but not who targeted them.",
		},
		{
			Name:   "a watcher",
			Wiki:   "Watcher",
			Flavor: "Each night, you may select one dwarf to watch. If they are targeted by an action during that night, you will know who targeted them, but not what the action was.",
		},
		{
			Name:   "a friendly neighbor",
			Wiki:   "Friendly_Neighbor",
			Flavor: "Each night, you may select one dwarf. You will leave a message for that dwarf proving you are not a vampire.",
		},
		{
			Name:   "only four years old",
			Wiki:   "Innocent_Child",
			Flavor: "At any point during the game, you may ask me to confirm that you are not a vampire in the public thread.",
		},
		// Note: skipped Mason as we cannot guarantee that there will
		// be more than one.
		{
			Name:   "a vigilante",
			Wiki:   "Vigilante",
			Flavor: "Each night, you may choose to kill one suspected vampire. You may only use this ability twice in the course of the game.",
		},
	}

	rolesScum := []Role{
		{
			Name:   "a night watchdwarf vampire",
			Wiki:   "Bodyguard",
			Flavor: goonFlavor + " Each night, you may select one dwarf (including vampires) to protect. If they are in danger, you will give your life to protect theirs.",
		},
		{
			Name:   "a vampire doctor",
			Wiki:   "Doctor",
			Flavor: goonFlavor + " Each night, you may select one dwarf (including vampires) to protect. Your target will be protected from one night kill attempt. You will not be told if your protection was successful.",
		},
		{
			Name:   "a vampire follower",
			Wiki:   "Follower",
			Flavor: goonFlavor + " Each night, you may select one dwarf (including vampires) to watch. If they perform an action during that night, you will know what the action was, but not who they targeted.",
		},
		{
			Name:   "a dabbler in many trades and also a vampire",
			Wiki:   "Jack_of_All_Trades",
			Flavor: goonFlavor + " Each night, you may select one dwarf (including vampires) to investigate, protect, kill, or distract. Investigating a dwarf tells you that dwarf's role, protecting a dwarf blocks one night kill attempt on them, killing a dwarf does not count towards your feeding quota, and distracting a dwarf prevents their night action. Each of these abilities may only be used once during the game.",
		},
		{
			Name:   "the vampire sheriff",
			Wiki:   "Jailkeeper",
			Flavor: goonFlavor + " Each night, you may lock one dwarf (including vampires) in a cage. This prevents them from acting but also prevents them from being killed. You may not lock yourself in a cage.",
		},
		{
			Name:   "a vampire door enthusiast",
			Wiki:   "Motion_Detector",
			Flavor: goonFlavor + " Each night, you may select one dwarf (including vampires) to watch. You will know if someone entered or left their bedroom after they were asleep, but not who or for what reason.",
		},
		// Note: skipped Neighbor and Neighborizer as the setup already
		// includes neighborhoods for all players.
		{
			Name:   "a drunk vampire",
			Wiki:   "Roleblocker",
			Flavor: goonFlavor + " Each night, you may select one dwarf (including vampires) to distract. A distracted dwarf will forget to perform an action at night.",
		},
		{
			Name:   "a vampire detective",
			Wiki:   "Rolecop",
			Flavor: goonFlavor + " Each night, you may select one dwarf (including vampires) to investigate. If successful, you will determine their role.",
		},
		{
			Name:   "a terribly flatulent vampire",
			Wiki:   "Rolestopper",
			Flavor: goonFlavor + " Each night, you may select one dwarf (including vampires) to visit. Your farts smell so terrible that nobody will come near them.",
		},
		{
			Name:   "a vampire stalker",
			Wiki:   "Tracker",
			Flavor: goonFlavor + " Each night, you may select one dwarf (including vampires) to follow. If successful, you will know who they visited during the night, but not what they did during the visit.",
		},
		{
			Name:   "a grave-robbing vampire",
			Wiki:   "Universal_Backup",
			Flavor: goonFlavor + " You will inherit the special ability of the first dwarf (including vampires) to die with one.",
		},
		// Note: skipped Vanilla Cop
		{
			Name:   "a vampire voyeur",
			Wiki:   "Voyeur",
			Flavor: goonFlavor + " Each night, you may select one dwarf (including vampires) to watch. If they are targeted by an action during that night, you will know what the action was, but not who targeted them.",
		},
		{
			Name:   "a vampire watcher",
			Wiki:   "Watcher",
			Flavor: goonFlavor + " Each night, you may select one dwarf (including vampires) to watch. If they are targeted by an action during that night, you will know who targeted them, but not what the action was.",
		},
		// Note: skipped Encryptor as the setup does not have a night
		// phase.
		{
			Name:   "a very stealthy vampire",
			Wiki:   "Ninja",
			Flavor: goonFlavor + " Your movements will not be detected by any investigative ability.",
		},
		{
			Name:   "a very strong vampire",
			Wiki:   "Strongman",
			Flavor: goonFlavor + " You may additionally request that the kill is unblockable. This ability can be used twice in the course of the game.",
		},
		// Note: skipped Traitor as it would make role PMs harder
	}

	powers := r.Perm(flag.NArg())[:flag.NArg()/4+r.Intn(flag.NArg()/4)]
	scum := r.Perm(flag.NArg())[:2+r.Intn(flag.NArg()/3)]

	for _, i := range scum {
		players[i].Scum = true
		players[i].RoleName = "a vampire"
		players[i].RoleWiki = "Goon"
		players[i].RoleFlavor = goonFlavor
		players[i].WinCondition = "the only citizens left in the fortress are vampires or nothing can prevent this from occurring"
	}

	for _, i := range powers {
		var role Role
		if players[i].Scum {
			role = rolesScum[r.Intn(len(rolesScum))]
		} else {
			role = rolesTown[r.Intn(len(rolesTown))]
		}

		players[i].RoleName = role.Name
		players[i].RoleWiki = role.Wiki
		players[i].RoleFlavor = role.Flavor
	}

	if err := tmpl.Funcs(template.FuncMap{
		"ShufflePlayers": func() []Player {
			index := r.Perm(len(players))
			shuffled := make([]Player, len(players))
			for i, j := range index {
				shuffled[i] = players[j]
			}
			return shuffled
		},
	}).Execute(os.Stdout, map[string]interface{}{
		"Players":   players,
		"Burrows":   burrows,
		"Moderator": *moderator,
	}); err != nil {
		panic(err)
	}
}
